- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/pet.rb
- app/models/spotted.rb
- config/initializers/geocoder.rb
- package.json
- yarn.lock
**PLEASE READ ME:**
heroku config:set **PENDING**
controller config **PENDING**
commits to check:
**API**
(env) mapbox api key added
**BUNDLE AND YARN INSTALL NECESSARY:**
**Gems and Yarn**
(gem) gems added: geocoder, 
(yarn) mapbox
**ES6**
(javascript) map construction added - plugin added
(javascript) application to import plugin
(css) import mapbox external library
**Models**
(added) spotted to be geocoded by address
> geocoder setup

- app/javascript/packs/application.js
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- config/locales/devise.en.yml
- package.json
- yarn.lock
added Inputmask (JS) for input mask set up
> included user's first_name, last_name and phone

- app/controllers/pages_controller.rb
- app/controllers/pets_controller.rb
- app/views/pages/my_profile.html.erb
> My profile

- app/controllers/pages_controller.rb
- app/controllers/pets_controller.rb
- app/models/pet.rb
- app/views/pages/home.html.erb
- app/views/pages/my_profile.html.erb
- app/views/pets/index.html.erb
- app/views/pets/show.html.erb
cloudinary is now functional on local host - test heroku.
all image references pulling from model attached photo
> cloudinary working on local host

- app/javascript/packs/application.js
inputmask prevented from becoming a headache
> inputmask prevented from becoming a headache

- app/controllers/pets_controller.rb
- app/views/pages/home.html.erb
- app/views/pages/my_profile.html.erb
- app/views/pets/index.html.erb
@alexandrecastello  to review merge conflicts on pets_controller to update pets
acredito que sera necessario alterar view do pet/show - remover botão de "achei meu pet" depois que ele foi encontrado
> hide seen pets from views

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pets/show.html.erb
Also added logic to hide buttons if pet has already been found.
> Small layout changes on Pet page

- app/views/pets/new.html.erb
- app/views/spotteds/new.html.erb
fixed form-algolia connection bug (autocomplete should be functional - tested on ticket)
> fix form-algolia connection bug

- app/controllers/pets_controller.rb
- app/views/layouts/application.html.erb
- app/views/pets/index.html.erb
- app/views/spotteds/poster.html.erb
beginning of facebook-share option implementation
pending: check if fb pulls imgkit url when called on production.
pending: let posters be pretty again (work on poster html)
pending: remove js script from index html (import js script instead)
notes: fb sharing option seems to only accept fb button class
> Imgkit poster fbshare

- app/views/pets/index.html.erb
This allows for better visualization on website and mobile
> Changed col rules for ards displayed on pets index

- app/controllers/spotteds_controller.rb
- app/models/spotted.rb
- app/views/spotteds/_map_info_window.html.erb
- app/views/spotteds/new.html.erb
**PLEASE READ**
unable to test spotted image on map info-box at pets/:id/show
map on localhost:3000 not working.
> spotted to receive one image as attachment

- app/views/layouts/application.html.erb
- app/views/pets/index.html.erb
- app/views/spotteds/poster.html.erb
se isso n der certo em producao:
retirar imgkit.jog da og:image
> ultima tentativa com fbshare + imgkit

- app/controllers/pets_controller.rb
Reverts alexandrecastello/rails-robyn#101
> Revert "Changes on PDF layout"

- app/views/layouts/application.html.erb
change applic meta tag conditional from .present? to .nil? - prevent new-pet page from break
> change applic meta tag conditional from .present? to .nil? 

- app/controllers/pets_controller.rb
Reverts alexandrecastello/rails-robyn#110
> Revert "Revert "Changes on PDF layout""

- app/views/layouts/application.html.erb
> fix condition on fb meta tags

- app/views/layouts/application.html.erb
imgkit abandoned due to download issues
Index share button will refer to pet page (pets/:pet_id) and preview pet info like below
```
<% if @pet.present? %>
<meta property="og:description"   content='Perdido desde <%= @pet.lost_date %>! Visto pela última vez em <%= @pet.lost_location.split(', ')[-3] %>. Nos ajude nesta busca! ' />
<meta property="og:title"         content="AJUDE A ENCONTRAR <%=@pet.name&.upcase%>" />
<meta property="og:image"         content='<%= (@pet.photo.attached? ? (cl_image_path @pet.photo.key) : (image_path "placeholder.png")) %>' />
<meta property="og:url"           content='https://robyn.com.br/pets/<%="#{@pet.id}"%>/' />
<% end %>
```
> change fb meta tags to mimic a poster on page preview.

- app/views/layouts/application.html.erb
meta tags added:
fb preview image sizing set directly on og:image setup.
```
<meta property="og:type"          content='website'/>
<meta property="og:image:width"   content="1200" />
<meta property="og:image:height"  content="630" />
```
> appl meta tags to comply to lewagon setup

- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- Removed messages link on navbar
- Fixed target on footer links
> Minor fixes

- app/views/pets/index.html.erb
- app/views/pets/show.html.erb
> move fb share button from index page to show page

- app/views/pets/show.html.erb
url do botao tava faltando endereço
> button missing url location

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
Improvements on media queries, plus minor enhancements on code legibility. Still a lot to improve on CSS, but I'll leave it to the next commit. Tested across different resolutions using Inspect on Google Chrome.
Related to issue #145.
> Media queries refactored, plus enhancements on code legibility
